package hardroid.quiz.season1;

import hardroid.quiz.R;

public class Level6_Array {
    final  int[] images6 = {
            R.drawable.s1_level6_weight1,
            R.drawable.s1_level6_weight2,
            R.drawable.s1_level6_weight3,
            R.drawable.s1_level6_weight4,
            R.drawable.s1_level6_weight5,
            R.drawable.s1_level6_weight6,
            R.drawable.s1_level6_weight7,
            R.drawable.s1_level6_weight8,
            R.drawable.s1_level6_weight9,
            R.drawable.s1_level6_weight10,
            R.drawable.s1_level6_weight11,
            R.drawable.s1_level6_weight12,
            R.drawable.s1_level6_weight13,
            R.drawable.s1_level6_weight14,
            R.drawable.s1_level6_weight15,
            R.drawable.s1_level6_weight16,
            R.drawable.s1_level6_weight17,
            R.drawable.s1_level6_weight18,
            R.drawable.s1_level6_weight19,
            R.drawable.s1_level6_weight20,
            R.drawable.s1_level6_weight21,
            R.drawable.s1_level6_weight22,
            R.drawable.s1_level6_weight23,
            R.drawable.s1_level6_weight24,
            R.drawable.s1_level6_weight25,
            R.drawable.s1_level6_weight26,
            R.drawable.s1_level6_weight27,
            R.drawable.s1_level6_weight28,
            R.drawable.s1_level6_weight29,
            R.drawable.s1_level6_weight30,
            R.drawable.s1_level6_weight31,
            R.drawable.s1_level6_weight32,
            R.drawable.s1_level6_weight33,
            R.drawable.s1_level6_weight34,
            R.drawable.s1_level6_weight35,
            R.drawable.s1_level6_weight36,
            R.drawable.s1_level6_weight37,
            R.drawable.s1_level6_weight38,
            R.drawable.s1_level6_weight39,
            R.drawable.s1_level6_weight40,
            R.drawable.s1_level6_weight41,
            R.drawable.s1_level6_weight42,
            R.drawable.s1_level6_weight43,
            R.drawable.s1_level6_weight44,
            R.drawable.s1_level6_weight45,
            R.drawable.s1_level6_weight46,
            R.drawable.s1_level6_weight47,
            R.drawable.s1_level6_weight48,
            R.drawable.s1_level6_weight49,
            R.drawable.s1_level6_weight50
    };

    final int[] values = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,
    36,37,38,39,40,41,42,43,44,45,46,47,48,49,50};


    final int[] text6 = { //string text
            R.string.s1_l6_dust,
            R.string.s1_l6_tea_bag,
            R.string.s1_l6_cherry,
            R.string.s1_l6_cookie,
            R.string.s1_l6_battery_aa,
            R.string.s1_l6_apricot,
            R.string.s1_l6_budgie,
            R.string.s1_l6_weight_100g,
            R.string.s1_l6_apple,
            R.string.s1_l6_potato,
            R.string.s1_l6_pigeon,
            R.string.s1_l6_month_kitty,
            R.string.s1_l6_axe,
            R.string.s1_l6_bottle,
            R.string.s1_l6_laptop,
            R.string.s1_l6_wedding_dress,
            R.string.s1_l6_brick,
            R.string.s1_l6_cat,
            R.string.s1_l6_watermelon,
            R.string.s1_l6_empty_beer_keg,
            R.string.s1_l6_dog,
            R.string.s1_l6_wolf,
            R.string.s1_l6_woman,
            R.string.s1_l6_man,
            R.string.s1_l6_slight_motorbike,
            R.string.s1_l6_pig,
            R.string.s1_l6_amur_tiger,
            R.string.s1_l6_horse,
            R.string.s1_l6_bull,
            R.string.s1_l6_vaz_2102,
            R.string.s1_l6_nissanXtrail,
            R.string.s1_l6_gazelle,
            R.string.s1_l6_hippo,
            R.string.s1_l6_elephant,
            R.string.s1_l6_ural375,
            R.string.s1_l6_killer_whale,
            R.string.s1_l6_an30,
            R.string.s1_l6_container_20t,
            R.string.s1_l6_t34,
            R.string.s1_l6_cachalot,
            R.string.s1_l6_hoba_meteor,
            R.string.s1_l6_argentionosaurs,
            R.string.s1_l6_plane,
            R.string.s1_l6_cloud,
            R.string.s1_l6_rat_tank,
            R.string.s1_l6_engine,
            R.string.s1_l6_cargoship,
            R.string.s1_l6_moon,
            R.string.s1_l6_earth,
            R.string.s1_l6_black_hole
    };

}
